-- 国内精品肉铺：商品分类管理升级
-- 在 Supabase Dashboard → SQL Editor 中运行一次。

begin;

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  icon text not null default '🥩',
  description text not null default '',
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint categories_name_not_blank check (btrim(name) <> ''),
  constraint categories_name_unique unique (name)
);

alter table public.products
  add column if not exists category_id bigint references public.categories(id) on delete set null;

create index if not exists products_category_id_idx on public.products(category_id);
create index if not exists categories_sort_order_idx on public.categories(sort_order, id);

-- 从现有商品自动生成分类，旧商品不需要重新编辑。
insert into public.categories (name, icon, sort_order)
select category_name, '🥩', row_number() over (order by category_name) * 10
from (
  select distinct coalesce(nullif(btrim(category), ''), '其他') as category_name
  from public.products
) source
on conflict (name) do nothing;

update public.products p
set category_id = c.id,
    category = c.name
from public.categories c
where p.category_id is null
  and c.name = coalesce(nullif(btrim(p.category), ''), '其他');

create or replace function public.sync_product_category()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.category_id is not null then
    select name into new.category
    from public.categories
    where id = new.category_id;
  elsif nullif(btrim(new.category), '') is null then
    new.category := '其他';
  end if;
  return new;
end;
$$;

drop trigger if exists products_sync_category on public.products;
create trigger products_sync_category
before insert or update of category_id, category on public.products
for each row execute function public.sync_product_category();

create or replace function public.sync_category_rename()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.name is distinct from old.name then
    update public.products
    set category = new.name
    where category_id = new.id;
  end if;
  return new;
end;
$$;

drop trigger if exists categories_sync_rename on public.categories;
create trigger categories_sync_rename
after update of name on public.categories
for each row execute function public.sync_category_rename();

drop trigger if exists categories_set_updated_at on public.categories;
create trigger categories_set_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

alter table public.categories enable row level security;

drop policy if exists "public can view active categories" on public.categories;
create policy "public can view active categories"
on public.categories
for select
to anon, authenticated
using (is_active = true or public.is_admin());

drop policy if exists "admins can insert categories" on public.categories;
create policy "admins can insert categories"
on public.categories
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "admins can update categories" on public.categories;
create policy "admins can update categories"
on public.categories
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins can delete categories" on public.categories;
create policy "admins can delete categories"
on public.categories
for delete
to authenticated
using (public.is_admin());

-- 隐藏分类后，普通访客不会读取该分类下的商品；管理员仍可读取全部商品。
drop policy if exists "public can view active products" on public.products;
create policy "public can view active products"
on public.products
for select
to anon, authenticated
using (
  public.is_admin()
  or (
    is_active = true
    and (
      category_id is null
      or exists (
        select 1
        from public.categories c
        where c.id = products.category_id
          and c.is_active = true
      )
    )
  )
);

commit;

notify pgrst, 'reload schema';

-- 验证结果
select c.id, c.name, c.icon, c.sort_order, c.is_active, count(p.id) as product_count
from public.categories c
left join public.products p on p.category_id = c.id
group by c.id
order by c.sort_order, c.id;
