-- 国内精品肉铺：Supabase 初始化脚本
-- 在 Supabase Dashboard → SQL Editor 中一次性运行本文件。

begin;

create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '管理员',
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default '其他',
  image_url text,
  image_urls text[] not null default '{}'::text[],
  emoji text not null default '🥩',
  price_text text not null default '实时询价',
  stock_text text not null default '咨询库存',
  description text not null default '',
  is_active boolean not null default true,
  is_featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 已运行过旧版脚本的项目也可直接重跑，自动补充多图字段。
alter table public.products
  add column if not exists image_urls text[] not null default '{}'::text[];

update public.products
set image_urls = array[image_url]
where image_url is not null
  and btrim(image_url) <> ''
  and coalesce(cardinality(image_urls), 0) = 0;

create table if not exists public.store_settings (
  id smallint primary key default 1 check (id = 1),
  shop_name text not null default '国内精品肉铺',
  shop_subtitle text not null default '商品浏览 · 选品咨询',
  hero_tag text not null default '国内精品 · 实时咨询',
  hero_title text not null default '浏览全部商品，选好再咨询',
  hero_text text not null default '查看商品详情、价格、库存及配送说明。将感兴趣的商品加入选品清单后，可整体分享或一键联系官方客服。',
  bot_username text not null default 'TJ_ice_CS_bot',
  channel_username text not null default 'TJ_NO1_ice',
  group_username text not null default 'TJ_ice_Group',
  price_notice text not null default '页面为参考或实时询价，最终价格以客服确认为准。',
  stock_notice text not null default '库存随时变化，下单前请先咨询当日库存与规格。',
  delivery_notice text not null default '配送范围、时效及售后标准由客服根据地区说明。',
  anti_fraud_notice text not null default '仅认准官方客服、频道和群组，不向其他账号付款。',
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists store_settings_set_updated_at on public.store_settings;
create trigger store_settings_set_updated_at
before update on public.store_settings
for each row execute function public.set_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_profiles
    where user_id = auth.uid()
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

alter table public.admin_profiles enable row level security;
alter table public.products enable row level security;
alter table public.store_settings enable row level security;

drop policy if exists "admin can view own profile" on public.admin_profiles;
create policy "admin can view own profile"
on public.admin_profiles
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "public can view active products" on public.products;
create policy "public can view active products"
on public.products
for select
to anon, authenticated
using (is_active = true or public.is_admin());

drop policy if exists "admins can insert products" on public.products;
create policy "admins can insert products"
on public.products
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "admins can update products" on public.products;
create policy "admins can update products"
on public.products
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins can delete products" on public.products;
create policy "admins can delete products"
on public.products
for delete
to authenticated
using (public.is_admin());

drop policy if exists "public can view store settings" on public.store_settings;
create policy "public can view store settings"
on public.store_settings
for select
to anon, authenticated
using (true);

drop policy if exists "admins can insert store settings" on public.store_settings;
create policy "admins can insert store settings"
on public.store_settings
for insert
to authenticated
with check (public.is_admin());

drop policy if exists "admins can update store settings" on public.store_settings;
create policy "admins can update store settings"
on public.store_settings
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

insert into public.store_settings (id)
values (1)
on conflict (id) do nothing;

insert into public.products
  (name, category, emoji, price_text, stock_text, description, sort_order)
select *
from (
  values
    ('高品质猪肉','猪肉','🥩','实时询价','当日库存','高品质猪肉占位商品，可在后台替换具体部位、重量、产地和规格说明。',10),
    ('XX1','猪肉','🍖','实时询价','咨询库存','XX1 占位模板，可在后台修改商品名称、图片、分类、价格与详情。',20),
    ('XX2','精品','🥓','咨询报价','当日库存','XX2 占位模板，适合展示精品肉类或组合商品。',30),
    ('XX3','精品','🍗','咨询报价','咨询库存','XX3 占位模板，后续可替换为正式商品资料。',40),
    ('家庭鲜肉组合','组合','🧺','套餐询价','可预订','家庭组合占位商品，可填写具体搭配、重量和配送范围。',50),
    ('精选排骨','猪肉','🍖','实时询价','当日库存','精选排骨占位商品，实际价格和规格请联系官方客服。',60),
    ('精品牛肉','牛肉','🥩','实时询价','咨询库存','精品牛肉占位商品，可补充部位、等级和包装规格。',70),
    ('其他生鲜需求','其他','🛒','咨询报价','联系客服','没有找到需要的商品，可将具体需求直接发送给客服。',80)
) as seed(name, category, emoji, price_text, stock_text, description, sort_order)
where not exists (select 1 from public.products);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'product-images',
  'product-images',
  true,
  5242880,
  array['image/jpeg','image/png','image/webp','image/gif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "public can view product images" on storage.objects;
create policy "public can view product images"
on storage.objects
for select
to public
using (bucket_id = 'product-images');

drop policy if exists "admins can upload product images" on storage.objects;
create policy "admins can upload product images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'product-images'
  and public.is_admin()
);

drop policy if exists "admins can update product images" on storage.objects;
create policy "admins can update product images"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'product-images'
  and public.is_admin()
)
with check (
  bucket_id = 'product-images'
  and public.is_admin()
);

drop policy if exists "admins can delete product images" on storage.objects;
create policy "admins can delete product images"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'product-images'
  and public.is_admin()
);

commit;

notify pgrst, 'reload schema';

-- 创建管理员账号后的授权步骤：
-- 1. Supabase Dashboard → Authentication → Users → Add user。
-- 2. 把下方邮箱替换成你的管理员邮箱，再单独运行这段 SQL：
--
-- insert into public.admin_profiles (user_id, display_name)
-- select id, '店铺管理员'
-- from auth.users
-- where email = '你的管理员邮箱'
-- on conflict (user_id) do update
-- set display_name = excluded.display_name;